# Data Frames. Ejercicio

A partir del archivo csv de viviendas en venta ('realestate.csv'), deseamos localizar los que tienen más de 1000 pies cuadrados, tres dormitorios y dos o más baños, situados en una ciudad distinta de “Sacramento” y tener un precio entre 100.000$ y 150.000$. Nos interesa averiguart la siguiente información:
<ol>
    <li> El listado completo </li>
    <li> De ellos, obtén un listado por ciudades y número de baños </li>
    <li> El número total de pisos en nuestra tabla </li>
    <li> La media de los precios de los pisos de nuestra tabla </li>
</ol>

In [1]:
# Ejercicio sobre Dataframes

import pandas

realestate = pandas.read_csv('realestate.csv')

cond = (realestate["sq__ft"] > 1000)        \
     & (realestate["beds"] == 3)            \
     & (realestate["baths"] >= 1)           \
     & (realestate["city"] != "SACRAMENTO") \
     & (100000 <= realestate["price"])      \
     & (realestate["price"] <= 150000)

# 1. Listado completo

nuestra_seleccion = realestate[cond]

nuestra_seleccion

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
19,113 LEEWILL AVE,RIO LINDA,95673,CA,3,2,1356,Residential,Wed May 21 00:00:00 EDT 2008,121630,38.689999,-121.463220
20,6118 STONEHAND AVE,CITRUS HEIGHTS,95621,CA,3,2,1118,Residential,Wed May 21 00:00:00 EDT 2008,122000,38.707851,-121.320707
25,3828 BLACKFOOT WAY,ANTELOPE,95843,CA,3,2,1088,Residential,Wed May 21 00:00:00 EDT 2008,126640,38.709740,-121.373770
31,6768 MEDORA DR,NORTH HIGHLANDS,95660,CA,3,2,1152,Residential,Wed May 21 00:00:00 EDT 2008,134555,38.691161,-121.371920
33,7944 DOMINION WAY,ELVERTA,95626,CA,3,2,1116,Residential,Wed May 21 00:00:00 EDT 2008,138750,38.713182,-121.411227
36,5031 CORVAIR ST,NORTH HIGHLANDS,95660,CA,3,2,1082,Residential,Wed May 21 00:00:00 EDT 2008,147308,38.658246,-121.375469
174,1121 CREEKSIDE WAY,GALT,95632,CA,3,1,1080,Residential,Tue May 20 00:00:00 EDT 2008,106716,38.241514,-121.312199
176,3725 DON JULIO BLVD,NORTH HIGHLANDS,95660,CA,3,1,1051,Residential,Tue May 20 00:00:00 EDT 2008,111000,38.678950,-121.379406
178,10542 SILVERWOOD WAY,RANCHO CORDOVA,95670,CA,3,1,1098,Residential,Tue May 20 00:00:00 EDT 2008,120108,38.587156,-121.295778
183,2505 RHINE WAY,ELVERTA,95626,CA,3,2,1080,Residential,Tue May 20 00:00:00 EDT 2008,126000,38.717976,-121.407684
189,840 TRANQUIL LN,GALT,95632,CA,3,2,1266,Residential,Tue May 20 00:00:00 EDT 2008,140000,38.270617,-121.299205
357,3732 LANKERSHIM WAY,NORTH HIGHLANDS,95660,CA,3,1,1331,Residential,Mon May 19 00:00:00 EDT 2008,112500,38.689720,-121.378399
365,3726 JONKO AVE,NORTH HIGHLANDS,95660,CA,3,2,1207,Residential,Mon May 19 00:00:00 EDT 2008,119250,38.656131,-121.377265
372,201 CARLO CT,GALT,95632,CA,3,2,1080,Residential,Mon May 19 00:00:00 EDT 2008,122000,38.242270,-121.310320
380,7226 LARCHMONT DR,NORTH HIGHLANDS,95660,CA,3,2,1209,Residential,Mon May 19 00:00:00 EDT 2008,130000,38.699269,-121.376334
383,7032 FAIR OAKS BLVD,CARMICHAEL,95608,CA,3,2,1245,Condo,Mon May 19 00:00:00 EDT 2008,139500,38.628563,-121.328297
384,2421 SANTINA WAY,ELVERTA,95626,CA,3,2,1416,Residential,Mon May 19 00:00:00 EDT 2008,140000,38.718650,-121.407763
625,2361 LA LOMA DR,RANCHO CORDOVA,95670,CA,3,2,1115,Residential,Fri May 16 00:00:00 EDT 2008,116000,38.593680,-121.316054
631,6548 GRAYLOCK LN,NORTH HIGHLANDS,95660,CA,3,2,1272,Residential,Fri May 16 00:00:00 EDT 2008,124413,38.686061,-121.369949
880,6208 GRATTAN WAY,NORTH HIGHLANDS,95660,CA,3,1,1051,Residential,Thu May 15 00:00:00 EDT 2008,105000,38.679279,-121.376615
884,5628 GEORGIA DR,NORTH HIGHLANDS,95660,CA,3,1,1229,Residential,Thu May 15 00:00:00 EDT 2008,110000,38.669587,-121.379879
902,3604 KODIAK WAY,ANTELOPE,95843,CA,3,2,1206,Residential,Thu May 15 00:00:00 EDT 2008,142000,38.706175,-121.379776

In [2]:
# Ejercicio sobre Dataframes

import pandas

# 2. Listado por ciudades y número de baños

print(nuestra_seleccion.groupby(['city','baths']).size())

city             baths
ANTELOPE         2        2
CARMICHAEL       2        1
CITRUS HEIGHTS   2        1
ELVERTA          2        3
GALT             1        1
                 2        2
NORTH HIGHLANDS  1        4
                 2        5
RANCHO CORDOVA   1        1
                 2        1
RIO LINDA        2        1
dtype: int64

In [3]:
# 3. El número total de pisos en nuestra tabla

print(nuestra_seleccion.count())        # OJO: cuenta los totales de todas las columnas...

print()

print(nuestra_seleccion["city"].count()) # OJO: cuenta los totales de una columna (la primera por ejemplo)

street       22
city         22
zip          22
state        22
beds         22
baths        22
sq__ft       22
type         22
sale_date    22
price        22
latitude     22
longitude    22
dtype: int64

22

In [4]:
# 4. La media de los precios de los pisos de nuestra tabla

print(nuestra_seleccion["price"])

print()

print(nuestra_seleccion["price"].mean())

19     121630
20     122000
25     126640
31     134555
33     138750
36     147308
174    106716
176    111000
178    120108
183    126000
189    140000
357    112500
365    119250
372    122000
380    130000
383    139500
384    140000
625    116000
631    124413
880    105000
884    110000
902    142000
Name: price, dtype: int64

125244.09090909091